export const signupUrl = 'https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=AIzaSyDlOlMJ-4kWeEQPeC3sSYb8LBhRmT_1K80'
export const loginUrl = 'https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyDlOlMJ-4kWeEQPeC3sSYb8LBhRmT_1K80'
export const getUserUrl = 'https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=AIzaSyDlOlMJ-4kWeEQPeC3sSYb8LBhRmT_1K80'
export const defaultUrl = 'https://rchat-58440-default-rtdb.firebaseio.com/'
export const refreshTokenUrl = 'https://securetoken.googleapis.com/v1/token?key=AIzaSyDlOlMJ-4kWeEQPeC3sSYb8LBhRmT_1K80'
